services:
  bckupr:
    # image: sbnarra/bckupr
    build:
      context: ./
      args:
        VERSION: compose
    env_file:
      - path: ${ENV_FILE:-$PWD/.env}
        required: true
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
      - ${BACKUP_DIR:-/tmp/backups}:${BACKUP_DIR:-/tmp/backups}