services:
  bckupr:
    # image: sbnarra/bckupr:nightly
    build:
      context: ./
      args:
        VERSION: compose
    environment:
      DRY_RUN: ${DRY_RUN:-true}
      BACKUP_DIR: ${BACKUP_DIR:-/tmp/backups}
    volumes:
      - ${BACKUP_DIR:-/tmp/backups}:${BACKUP_DIR:-/tmp/backups}
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock