services:
  bckupr:
    image: sbnarra/bckupr:nightly
    env_file:
      - path: ./.env
        required: false
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
      - ${BACKUP_DIR:-/tmp/backups}:/backups