name: 'Publish Docker Image'
description: 'Publishes docker image'
inputs:
  dockerhub_username:
    description: 'Dockerhub username'
    required: true 
  dockerhub_token:
    description: 'Dockerhub token'
    required: true 
  publish_version:
    description: 'Version to publish'
    required: true
  buildx_args:
    description: 'Additional buildx args'
    required: false
runs:
  using: "composite"
  steps:
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}
    - shell: bash
      run: ./scripts/app-build-image.sh --push ${{ inputs.buildx_args }}
      env:
        VERSION: ${{ inputs.publish_version }}
        DOCKER_ARGS: --platform linux/amd64 
        # DOCKER_ARGS: --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/386,linux/ppc64le,linux/s390x