/**
 * Bckupr
 * Bckupr API
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Status from './Status';
import Volume from './Volume';

/**
 * The Restore model module.
 * @module model/Restore
 * @version latest
 */
class Restore {
    /**
     * Constructs a new <code>Restore</code>.
     * @alias module:model/Restore
     * @param id {String} 
     * @param started {Date} 
     * @param status {module:model/Status} 
     * @param volumes {Array.<module:model/Volume>} 
     */
    constructor(id, started, status, volumes) { 
        
        Restore.initialize(this, id, started, status, volumes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, started, status, volumes) { 
        obj['id'] = id;
        obj['started'] = started;
        obj['status'] = status;
        obj['volumes'] = volumes;
    }

    /**
     * Constructs a <code>Restore</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Restore} obj Optional instance to populate.
     * @return {module:model/Restore} The populated <code>Restore</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Restore();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('started')) {
                obj['started'] = ApiClient.convertToType(data['started'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = Status.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('volumes')) {
                obj['volumes'] = ApiClient.convertToType(data['volumes'], [Volume]);
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Restore</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Restore</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Restore.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        if (data['volumes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['volumes'])) {
                throw new Error("Expected the field `volumes` to be an array in the JSON data but got " + data['volumes']);
            }
            // validate the optional field `volumes` (array)
            for (const item of data['volumes']) {
                Volume.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }

        return true;
    }


}

Restore.RequiredProperties = ["id", "started", "status", "volumes"];

/**
 * @member {String} id
 */
Restore.prototype['id'] = undefined;

/**
 * @member {Date} started
 */
Restore.prototype['started'] = undefined;

/**
 * @member {module:model/Status} status
 */
Restore.prototype['status'] = undefined;

/**
 * @member {Array.<module:model/Volume>} volumes
 */
Restore.prototype['volumes'] = undefined;

/**
 * @member {String} error
 */
Restore.prototype['error'] = undefined;






export default Restore;

