/**
 * Bckupr
 * Bckupr API
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RotateInput model module.
 * @module model/RotateInput
 * @version latest
 */
class RotateInput {
    /**
     * Constructs a new <code>RotateInput</code>.
     * @alias module:model/RotateInput
     * @param policiesPath {String} 
     * @param destroy {Boolean} 
     */
    constructor(policiesPath, destroy) { 
        
        RotateInput.initialize(this, policiesPath, destroy);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, policiesPath, destroy) { 
        obj['policies_path'] = policiesPath;
        obj['destroy'] = destroy;
    }

    /**
     * Constructs a <code>RotateInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RotateInput} obj Optional instance to populate.
     * @return {module:model/RotateInput} The populated <code>RotateInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RotateInput();

            if (data.hasOwnProperty('no_dry_run')) {
                obj['no_dry_run'] = ApiClient.convertToType(data['no_dry_run'], 'Boolean');
            }
            if (data.hasOwnProperty('policies_path')) {
                obj['policies_path'] = ApiClient.convertToType(data['policies_path'], 'String');
            }
            if (data.hasOwnProperty('destroy')) {
                obj['destroy'] = ApiClient.convertToType(data['destroy'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RotateInput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RotateInput</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RotateInput.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['policies_path'] && !(typeof data['policies_path'] === 'string' || data['policies_path'] instanceof String)) {
            throw new Error("Expected the field `policies_path` to be a primitive type in the JSON string but got " + data['policies_path']);
        }

        return true;
    }


}

RotateInput.RequiredProperties = ["policies_path", "destroy"];

/**
 * @member {Boolean} no_dry_run
 * @default false
 */
RotateInput.prototype['no_dry_run'] = false;

/**
 * @member {String} policies_path
 */
RotateInput.prototype['policies_path'] = undefined;

/**
 * @member {Boolean} destroy
 */
RotateInput.prototype['destroy'] = undefined;






export default RotateInput;

