/**
 * Bckupr
 * Bckupr API
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class StopModes.
* @enum {}
* @readonly
*/
export default class StopModes {
    
        /**
         * value: "all"
         * @const
         */
        "all" = "all";

    
        /**
         * value: "labelled"
         * @const
         */
        "labelled" = "labelled";

    
        /**
         * value: "writers"
         * @const
         */
        "writers" = "writers";

    
        /**
         * value: "attached"
         * @const
         */
        "attached" = "attached";

    
        /**
         * value: "linked"
         * @const
         */
        "linked" = "linked";

    

    /**
    * Returns a <code>StopModes</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/StopModes} The enum <code>StopModes</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

