push:
  image: amazon/aws-cli
  env: 
    - BUCKET
    - AWS_SECRET
    - AWS_SECRET_KEY
  cmd:
    - aws
    - s3
    - cp
    - $BACKUP_DIR/$BACKUP_ID/$VOLUME_NAME.$FILE_EXT
    - s3://$BUCKET/$BACKUP_ID/$VOLUME_NAME.$FILE_EXT
pull:
  image: amazon/aws-cli
  env: 
    - AWS_SECRET
    - AWS_SECRET_KEY
  cmd:
    - aws
    - s3
    - cp
    - s3://$BUCKET/$BACKUP_ID/$VOLUME_NAME.$FILE_EXT
    - $BACKUP_DIR/$BACKUP_ID/$VOLUME_NAME.$FILE_EXT