/* tslint:disable */
/* eslint-disable */
/**
 * Bckupr
 * Bckupr API
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RotateInput
 */
export interface RotateInput {
    /**
     * 
     * @type {boolean}
     * @memberof RotateInput
     */
    noDryRun?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RotateInput
     */
    policiesPath: string;
    /**
     * 
     * @type {boolean}
     * @memberof RotateInput
     */
    destroy: boolean;
}

/**
 * Check if a given object implements the RotateInput interface.
 */
export function instanceOfRotateInput(value: object): boolean {
    if (!('policiesPath' in value)) return false;
    if (!('destroy' in value)) return false;
    return true;
}

export function RotateInputFromJSON(json: any): RotateInput {
    return RotateInputFromJSONTyped(json, false);
}

export function RotateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RotateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'noDryRun': json['no_dry_run'] == null ? undefined : json['no_dry_run'],
        'policiesPath': json['policies_path'],
        'destroy': json['destroy'],
    };
}

export function RotateInputToJSON(value?: RotateInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'no_dry_run': value['noDryRun'],
        'policies_path': value['policiesPath'],
        'destroy': value['destroy'],
    };
}

