// Package spec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package spec

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for Status.
const (
	StatusCompleted Status = "completed"
	StatusError     Status = "error"
	StatusPending   Status = "pending"
	StatusRunning   Status = "running"
)

// Defines values for StopModes.
const (
	All      StopModes = "all"
	Attached StopModes = "attached"
	Labelled StopModes = "labelled"
	Linked   StopModes = "linked"
	Writers  StopModes = "writers"
)

// Backup defines model for Backup.
type Backup struct {
	Created time.Time `json:"created"`
	Id      string    `json:"id"`
	Status  Status    `json:"status"`
	Type    string    `json:"type"`
	Volumes []Volume  `json:"volumes"`
}

// ContainersConfig defines model for ContainersConfig.
type ContainersConfig struct {
	Filters     Filters      `json:"filters"`
	LabelPrefix *string      `json:"label_prefix,omitempty"`
	StopModes   *[]StopModes `json:"stop_modes,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Filters defines model for Filters.
type Filters struct {
	ExcludeNames   []string `json:"exclude_names"`
	ExcludeVolumes []string `json:"exclude_volumes"`
	IncludeNames   []string `json:"include_names"`
	IncludeVolumes []string `json:"include_volumes"`
}

// Restore defines model for Restore.
type Restore struct {
	Error   *string   `json:"error,omitempty"`
	Started time.Time `json:"started"`
	Status  Status    `json:"status"`
}

// Rotate defines model for Rotate.
type Rotate struct {
	Error   *string   `json:"error,omitempty"`
	Started time.Time `json:"started"`
	Status  Status    `json:"status"`
}

// RotateInput defines model for RotateInput.
type RotateInput struct {
	Destroy      bool   `json:"destroy"`
	PoliciesPath string `json:"policies_path"`
}

// Status defines model for Status.
type Status string

// StopModes defines model for StopModes.
type StopModes string

// Version defines model for Version.
type Version struct {
	Created string `json:"created"`
	Version string `json:"version"`
}

// Volume defines model for Volume.
type Volume struct {
	Created time.Time `json:"created"`
	Error   *string   `json:"error,omitempty"`
	Ext     string    `json:"ext"`
	Mount   string    `json:"mount"`
	Name    string    `json:"name"`
	Size    *int64    `json:"size,omitempty"`
	Status  Status    `json:"status"`
}

// Backups defines model for Backups.
type Backups = []Backup

// NotFound defines model for NotFound.
type NotFound = Error

// StartBackupJSONRequestBody defines body for StartBackup for application/json ContentType.
type StartBackupJSONRequestBody = ContainersConfig

// StartBackupWithIdJSONRequestBody defines body for StartBackupWithId for application/json ContentType.
type StartBackupWithIdJSONRequestBody = ContainersConfig

// StartRestoreJSONRequestBody defines body for StartRestore for application/json ContentType.
type StartRestoreJSONRequestBody = ContainersConfig

// RotateBackupsJSONRequestBody defines body for RotateBackups for application/json ContentType.
type RotateBackupsJSONRequestBody = RotateInput

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/backups)
	ListBackups(c *gin.Context)
	// Creates new backup
	// (POST /api/backups)
	StartBackup(c *gin.Context)
	// Deletes backup
	// (DELETE /api/backups/{id})
	DeleteBackup(c *gin.Context, id string)
	// Gets backup by id
	// (GET /api/backups/{id})
	GetBackup(c *gin.Context, id string)

	// (PUT /api/backups/{id})
	StartBackupWithId(c *gin.Context, id string)

	// (GET /api/backups/{id}/restore)
	GetRestore(c *gin.Context, id string)

	// (POST /api/backups/{id}/restore)
	StartRestore(c *gin.Context, id string)
	// Retrieves application version
	// (POST /api/rotate)
	RotateBackups(c *gin.Context)
	// Retrieves application version
	// (GET /api/version)
	GetVersion(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListBackups operation middleware
func (siw *ServerInterfaceWrapper) ListBackups(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListBackups(c)
}

// StartBackup operation middleware
func (siw *ServerInterfaceWrapper) StartBackup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartBackup(c)
}

// DeleteBackup operation middleware
func (siw *ServerInterfaceWrapper) DeleteBackup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteBackup(c, id)
}

// GetBackup operation middleware
func (siw *ServerInterfaceWrapper) GetBackup(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetBackup(c, id)
}

// StartBackupWithId operation middleware
func (siw *ServerInterfaceWrapper) StartBackupWithId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartBackupWithId(c, id)
}

// GetRestore operation middleware
func (siw *ServerInterfaceWrapper) GetRestore(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRestore(c, id)
}

// StartRestore operation middleware
func (siw *ServerInterfaceWrapper) StartRestore(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartRestore(c, id)
}

// RotateBackups operation middleware
func (siw *ServerInterfaceWrapper) RotateBackups(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RotateBackups(c)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVersion(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/backups", wrapper.ListBackups)
	router.POST(options.BaseURL+"/api/backups", wrapper.StartBackup)
	router.DELETE(options.BaseURL+"/api/backups/:id", wrapper.DeleteBackup)
	router.GET(options.BaseURL+"/api/backups/:id", wrapper.GetBackup)
	router.PUT(options.BaseURL+"/api/backups/:id", wrapper.StartBackupWithId)
	router.GET(options.BaseURL+"/api/backups/:id/restore", wrapper.GetRestore)
	router.POST(options.BaseURL+"/api/backups/:id/restore", wrapper.StartRestore)
	router.POST(options.BaseURL+"/api/rotate", wrapper.RotateBackups)
	router.GET(options.BaseURL+"/api/version", wrapper.GetVersion)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xYTW/jNhD9KwLbI7sy2qAodOumm0WAtigSID0EQUBL45i7EsmSo2xcQ/+9IClRX3Rs",
	"xy6w7U2myDdvHudL3pJcVkoKEGhItiUajJLCgPvxnuWfa2WfcikQBNpHplTJc4ZcivSTkcKumXwNFbNP",
	"32pYkYx8k/awqX9r0hauaRpKCjC55sqikKwz1ND2yRxlkyNU5lDjlOBGAckI05ptdpMxduvvEq9kLYqz",
	"SfBBa6ljRj8I5LhJhMRk5Sw2lNyAQanhbMY7vIj58IqSG4kMz2jUw8Vstm8ouQNtuAc9i80OL2K0f0Vb",
	"sEmkKy0VaOQ+A3INDMHd/0rqiiHJSMEQvkNeAQmxZFBz8WRd4W5vAStWl3ZzvgYw0Z0GGdZ7w/bW7wph",
	"u50DPcuyrjzdgzLhzu2PZAIlGv6qubb+3ltPaPC/3RtY91YfAoxcfoIcLe6lFMi4AG0upVjxp7muK14i",
	"6L1Ur9ptDSUlW0L5qDSs+MtY4qW9Oh2XWKrHShZHiHOLUv3mTuzTp3MhJoBP85nX0C1PmE6Q/bYY7lUv",
	"2wT5JS/rAh4FayMhyHP/QHvPZwqNPaQBZxBTb0Ti4jyMOpxTGU2je0RvboZOJJ1LE7ufQcU+7OZdQumj",
	"KsxxdWPidmctwES9CB3gP+/EtVA1zj0pwKCWm4EvSylLYMKeVLLkOQfzqBiu92freDsN2DFSt8Htvnwp",
	"EIXFpQREXTnEsKJrIfyTVacE7/W0PvSy9tXLXlcLx8qStPWzdOe/aO6qCCUMkeVrt1hy8RmKKOqgPe/s",
	"jvOu1B/qfV28W7xbzONhomh3tG8/MS3bNnZ6y94d1vCC0fVK1iL+xhaLeIbwv2FEiQv88aKnwwXCE+iT",
	"c8MR8MwHzdoTfk3PxpXalWyzYzgOu/aa/PzHtWXLsYSwSAbXTEqGYNzNSAWCKU4y8kN73zY1nEcpUzxd",
	"9jP+Ezgd7f25Qe+6IBn5lRvshnA6/iL5frHYJUzYl4YB3jYB9mSsLt4meXD5bSJGb21RacdALykYfC+L",
	"zdmm0tlUtPPbI0GZLCHph6/+hlHX0LxdFD/31lXF9IZk5NJZMImAL8my830mWUNH95ZuedH4OLEVaS7l",
	"L259oOWc69hr98XTERgz9FjmFXY0HkQfAV9lcJhalFwsLvZvD9+JY/IfATvmyXKTuIk6FpBMswr8YHc/",
	"1aY97s5yu9C2GV9p/JQ+Dg86iMdpoX2gpG2IO6P/T47r6+Jry4FTY/6goLZHu/ltV1B1I95b+PQf4F9D",
	"HOwug0Mf/2918NU76IJC9xNwVCU/XA571PllGg6w/2qWhH9ohqXrBlBzeAaTDDxI+smsk85sDEI1kG4w",
	"9+1KobuAcjzZ0f83J7C1x0E/d7lW65JkZI2osjQtZc7KtTSY/bRYLIhNlhZg26Vb16toWGmhm4fmnwAA",
	"AP//YA3CuVMVAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
