services:
  bckupr:
    environment:
      METRICS_ENABLED: true
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    # ports:
    #   - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "8000:3000"