/*
 * Bckupr
 *
 * Bckupr API Specification
 *
 * API version: latest
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spec

import (
	"github.com/gin-gonic/gin"
)

type BackupAPI interface {


    // CreateBackup Post /backups
    // Creates new backup 
     CreateBackup(c *gin.Context)

    // DeleteBackup Delete /backups/:id
    // Deletes backup 
     DeleteBackup(c *gin.Context)

    // GetBackup Get /backups/:id
    // Gets backup by id 
     GetBackup(c *gin.Context)

    // RestoreBackup Post /backups/:id/restore
     RestoreBackup(c *gin.Context)

}