/*
 * Bckupr
 *
 * Bckupr API Specification
 *
 * API version: latest
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spec

import (
	"github.com/gin-gonic/gin"
)

type SystemAPI interface {


    // GetVersion Get /version
    // Retrieves application version 
     GetVersion(c *gin.Context)

}