/*
 * Bckupr
 *
 * Bckupr API Specification
 *
 * API version: latest
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spec

type Task struct {

	LabelPrefix string `json:"label_prefix"`

	StopModes []string `json:"stop_modes"`

	Other []string `json:"other"`
}
