/*
 * Bckupr
 *
 * Bckupr API Specification
 *
 * API version: latest
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spec

type RestoreBackup struct {

	Id int32 `json:"id,omitempty"`
}
