/*
 * Bckupr
 *
 * Bckupr API Specification
 *
 * API version: latest
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spec

import (
	"time"
)

type Version struct {

	Version string `json:"version,omitempty"`

	Created time.Time `json:"created,omitempty"`
}
