/*
 * Bckupr
 *
 * Bckupr API Specification
 *
 * API version: latest
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spec

type Error struct {

	Error string `json:"error,omitempty"`
}
