/*
 * Bckupr
 *
 * Bckupr API Specification
 *
 * API version: latest
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spec

import (
	"time"
)

type Backup struct {

	Id int32 `json:"id,omitempty"`

	Created time.Time `json:"created,omitempty"`

	Status string `json:"status,omitempty"`
}
