/*
 * Bckupr
 *
 * Bckupr API Specification
 *
 * API version: latest
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package spec

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the BackupAPI part of the API
	BackupAPI BackupAPI
	// Routes for the SystemAPI part of the API
	SystemAPI SystemAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"CreateBackup",
			http.MethodPost,
			"/backups",
			handleFunctions.BackupAPI.CreateBackup,
		},
		{
			"DeleteBackup",
			http.MethodDelete,
			"/backups/:id",
			handleFunctions.BackupAPI.DeleteBackup,
		},
		{
			"GetBackup",
			http.MethodGet,
			"/backups/:id",
			handleFunctions.BackupAPI.GetBackup,
		},
		{
			"RestoreBackup",
			http.MethodPost,
			"/backups/:id/restore",
			handleFunctions.BackupAPI.RestoreBackup,
		},
		{
			"GetVersion",
			http.MethodGet,
			"/version",
			handleFunctions.SystemAPI.GetVersion,
		},
	}
}
