site_name: Bckupr
site_url: https://sbnarra.github.io/bckupr
repo_name: sbnarra/bckupr
repo_url: https://github.com/sbnarra/bckupr
docs_dir: .
dev_addr: 0.0.0.0:8000
theme: 
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      primary: black
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  features:
    - navigation.expand
markdown_extensions:
    - toc:
        permalink: True
        separator: "_"
    # - admonition
    # - pymdownx.highlight
    - pymdownx.tilde
    - pymdownx.superfences:
    - pymdownx.magiclink:
        repo_url_shortener: True
        provider: github
        user: bckupr
        repo: bckupr
    # - pymdownx.saneheaders
    - pymdownx.tabbed:
        alternate_style: true
plugins:
  - search:
  - include-markdown:
      preserve_includer_indent: true
      comments: false
      # dedent: false
      # trailing_newlines: false
      # rewrite_relative_urls: true
nav:
  - 'Introduction': index.md
  - 'Usage': usage.md
  - 'Commands':
      'Daemon': command/daemon.md
      'Cron': command/cron.md
      'Backup': command/backup.md
      'Restore': command/restore.md
      'Rotate': command/rotation.md
      'List': command/list.md
      'Delete': command/delete.md
  - 'Labels': 'labels.md'
  - 'Offsite': 'offsite.md'
  - 'Notifications': 'notifications.md'
  - 'Metrics': 'metrics.md'