/*
Bckupr

Bckupr API Specification

API version: latest
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the CreateBackup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBackup{}

// CreateBackup struct for CreateBackup
type CreateBackup struct {
	Id *string `json:"id,omitempty"`
}

// NewCreateBackup instantiates a new CreateBackup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBackup() *CreateBackup {
	this := CreateBackup{}
	return &this
}

// NewCreateBackupWithDefaults instantiates a new CreateBackup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBackupWithDefaults() *CreateBackup {
	this := CreateBackup{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateBackup) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBackup) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateBackup) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreateBackup) SetId(v string) {
	o.Id = &v
}

func (o CreateBackup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBackup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableCreateBackup struct {
	value *CreateBackup
	isSet bool
}

func (v NullableCreateBackup) Get() *CreateBackup {
	return v.value
}

func (v *NullableCreateBackup) Set(val *CreateBackup) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBackup) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBackup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBackup(val *CreateBackup) *NullableCreateBackup {
	return &NullableCreateBackup{value: val, isSet: true}
}

func (v NullableCreateBackup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBackup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


