/*
Bckupr

Bckupr API Specification

API version: latest
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the RestoreBackup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestoreBackup{}

// RestoreBackup struct for RestoreBackup
type RestoreBackup struct {
	Id *int32 `json:"id,omitempty"`
}

// NewRestoreBackup instantiates a new RestoreBackup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestoreBackup() *RestoreBackup {
	this := RestoreBackup{}
	return &this
}

// NewRestoreBackupWithDefaults instantiates a new RestoreBackup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestoreBackupWithDefaults() *RestoreBackup {
	this := RestoreBackup{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RestoreBackup) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestoreBackup) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RestoreBackup) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *RestoreBackup) SetId(v int32) {
	o.Id = &v
}

func (o RestoreBackup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestoreBackup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableRestoreBackup struct {
	value *RestoreBackup
	isSet bool
}

func (v NullableRestoreBackup) Get() *RestoreBackup {
	return v.value
}

func (v *NullableRestoreBackup) Set(val *RestoreBackup) {
	v.value = val
	v.isSet = true
}

func (v NullableRestoreBackup) IsSet() bool {
	return v.isSet
}

func (v *NullableRestoreBackup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestoreBackup(val *RestoreBackup) *NullableRestoreBackup {
	return &NullableRestoreBackup{value: val, isSet: true}
}

func (v NullableRestoreBackup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestoreBackup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


