openapi: 3.0.0
servers:
  - url: 'http://localhost:8000'
info:
  title: Bckupr System
  description: Bckupr System
  version: latest
tags:
  - name: system
paths:
components:
  schemas:
    Version:
      type: object
      required:
        - version
        - created
      properties:
        version:
          type: string
          default: the-default-version
        created:
          type: string
          format: date-time