openapi: 3.0.0
servers:
  - url: 'http://localhost:8000'
info:
  description: Bckupr API
  version: latest
  title: Bckupr
tags:
  - name: backup
  - name: system
paths:
  /backups:
    post:
      operationId: triggerBackup
      summary: Creates new backup
      tags:
        - backup
      requestBody:
        description: Backup to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BackupTrigger'
        required: true
      responses:
        '200':
          $ref: '#/components/responses/Backup'
    get:
      operationId: listBackups
      tags:
        - backup
      responses:
        '200':
          $ref: '#/components/responses/Backups'
  /backups/{id}:
    parameters:
        - name: id
          in: path
          description: backup id
          required: true
          schema:
            type: string
    get:
      operationId: getBackup
      summary: Gets backup by id
      tags:
        - backup
      responses:
        '200':
          $ref: '#/components/responses/Backup'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      operationId: triggerBackupWithId
      tags:
        - backup
      requestBody:
        description: Backup to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BackupTrigger'
      responses:
        '200':
          description: created b
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Backup'
    delete:
      operationId: deleteBackup
      summary: Deletes backup
      tags:
        - backup
      responses:
        '200':
          description: found backup
  /backups/{id}/restore:
    parameters:
        - name: id
          in: path
          description: backup id
          required: true
          schema:
            type: string
    post:
      operationId: triggerRestore
      tags:
        - backup
      requestBody:
        description: Backup to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RestoreTrigger'
      responses:
        '200':
          $ref: '#/components/responses/Task'
  /rotate:
    post:
      operationId: rotateBackups
      summary: Retrieves application version
      tags:
        - system
      requestBody:
        description: Backup to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RotateTrigger'
      responses:
        '200':
          $ref: '#/components/responses/Task'
  /version:
    get:
      operationId: getVersion
      summary: Retrieves application version
      tags:
        - system
      responses:
        '200':
          description: Application Version
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
components:
  responses:
    Backup:
      description: Backup
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Backup'
    Backups:
      description: Backups
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Backup'
    Task:
      description: Task
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Task'
    NotFound:
      description: Entity not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Backup:
      type: object
      anyOf:
        - $ref: '#/components/schemas/Task'
      required:
        - id
        - created
        - type
        - volumes
      properties:
        id:
          type: string
        created:
          type: string
          format: date-time
        type:
          type: string
        volumes:
          type: array
          items:
            $ref: '#/components/schemas/Volume'
    Volume:
      type: object
      required:
        - name
        - ext
        - mount
        - created
        - size
        - error
      properties:
        name:
          type: string
        ext:
          type: string
        mount:
          type: string
        created:
          type: string
          format: date-time
        size:
          type: integer
          format: int64
        error:
          type: string
    Task:
      type: object
      required:
        - created
        - status
      properties:
        created:
          type: string
          format: date-time
        status:
          type: string
          enum:
            - pending
            - completed
            - error
    BackupTrigger:
      type: object
      anyOf:
        - $ref: '#/components/schemas/TaskTrigger'
      properties:
    RestoreTrigger:
      type: object
      anyOf:
        - $ref: '#/components/schemas/TaskTrigger'
      properties:
        dummy:
          type: string
    RotateTrigger:
      type: object
      required:
        - policies_path
        - destroy
      properties:
        policies_path:
          type: string
        destroy:
          type: boolean
    TaskTrigger:
      type: object
      required:
        - filters
      properties:
        label_prefix:
          type: string
          default: bckupr
        stop_modes:
          type: array
          items:
            $ref: '#/components/schemas/StopModes'
        filters:
          $ref: '#/components/schemas/Filters'
    StopModes:
      type: string
      enum:
        - all
        - labelled
        - writers
        - attached
        - linked
    Filters:
      type: object
      required:
        - include_names
        - include_volumes
        - exclude_names
        - exclude_volumes
      properties:
        include_names:
          type: array
          items:
            type: string
          default: []
        include_volumes:
          type: array
          items:
            type: string
          default: []
        exclude_names:
          type: array
          items:
            type: string
          default: []
        exclude_volumes:
          type: array
          items:
            type: string
          default: []
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
    Version:
      type: object
      required:
        - version
        - created
      properties:
        version:
          type: string
          default: 0.0.0
        created:
          type: string
         