name: Dependabot Auto-Merge
on:
  pull_request:
    branches:
      - development
    # types: [opened, synchronize, reopened]
jobs:
  test-app:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'dependabot/') }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/app/test
  publish-nightly-image:
    needs: test-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/app/publish
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          publish_version: nightly
  auto-merge:
    needs: publish-nightly-image
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - id: dependabot-metadata
        if: github.actor == 'dependabot[bot]'
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - run: gh pr merge --auto --merge "$PR_URL"
        if: ${{ steps.dependabot-metadata.result == 'skipped' || steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ github.token }}