name: Dependabot Auto-Merge
on:
  push:
    branches:
      - "dependabot/*"
  pull_request:
    branches:
      - development
    # types: [opened, synchronize, reopened]
jobs:
  build-app:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/dependabot/') }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/image/build
  publish-nightly-image:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/image/publish
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          publish_version: nightly
  auto-merge:
    needs: publish-nightly-image
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ github.token }}