name: Publish Edge (Image Only)
on:
  push:
    branches:
      - development
jobs:
  publish-edge-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/app/publish
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          publish_version: edge
          publish_dockerhub_readme: true